const productData = [
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "trending",
      "for": "kids",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 12,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "trending",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 3,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "trending",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 4,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "elderly",
      "category": "trending",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 5,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "women",
      "category": "trending",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 6,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "trending",
      "for": "men",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 7,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "trending",
      "for": "men",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 8,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "trending",
      "for": "men",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 9,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "trending",
      "for": "friends",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 10,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "trending",
      "for": "friends",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 11,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "friends",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 12,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "friends",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 13,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "kids",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 14,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "women",
      "category": "lifestyle",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 15,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "men",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 16,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "women",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 17,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 18,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 19,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 20,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "lifestyle",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 21,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "home decor",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "home decor",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "elderly",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "home decor",
      "for": "elderly",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "for": "elderly",
      "brand": "Apple",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "for": "elderly",
      "brand": "Apple",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "elderly",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "elderly",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "kids",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "kids",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "kids",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "kids",
      "category": "home decor",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "kids",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "kids",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "women",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "women",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "women",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "friends",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "friends",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "friends",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "friends",
      "category": "electronics",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "appliances",
      "for": "friends",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "category": "appliances",
      "for": "friends",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "women",
      "category": "appliances",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "women",
      "category": "appliances",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "women",
      "category": "appliances",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "men",
      "category": "appliances",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "men",
      "category": "appliances",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "men",
      "category": "appliances",
      "images": "Images/santa-ring.jpg"
    },
    {
      "id": 1,
      "title": "",
      "price": 549,
      "cutPric": 800,
      "discountPercentage": 12.96,
      "rating": 4.69,
      "stock": 94,
      "brand": "Apple",
      "for": "men",
      "category": "appliances",
      "images": "Images/santa-ring.jpg"
    },
    
  ]


  module.exports = {productData}
